### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by shpakb** [shpakb/cshw#2]

**Comment by YakutovDmitriy** [comment]
* `add_border`. Why are you printing result?
* `good_pairs`. You have a mistake here. Try to find it by yourself;
* Other functions are ok.

**Comment by YakutovDmitriy** [comment]
Also you have to add tests to your first hw

**Comment by shpakb** [comment]
Done

**Comment by YakutovDmitriy** [comment]
Everything os ok
