### ISSUE TITLE
Task 7

### ISSUE THREAD

**Issue by shpakb** [shpakb/cshw#7]

**Comment by YakutovDmitriy** [comment]
* `valuesunion` - try this: `valuesunion({1: 5}, {1: 10})`
* `popcount` - you have to calculate number of `1`-bits, not all bits
* `powers` - ok
* `subpalindrome` - you forgot about lexicographical order
* `fibonacci` - ok
* `pascals` - what is `n`?
* `isIPv4` - ok

Good job. Fix everything I've mensioned above

**Comment by shpakb** [comment]
I think I'm done.
