### ISSUE TITLE
Task 9

### ISSUE THREAD

**Issue by shpakb** [shpakb/cshw#9]

**Comment by YakutovDmitriy** [comment]
* `FSItem.create`. Now you decide if item is directory or not using `FSItem.isdirectory`. But this method returns `False` if current item does not exist in OS, so you always create current item as file. This issue should be solved using inheritance (create separate implementations for files and directories in `File.create` and `Directory.create`)
* `File.getcontent`. You open a file twice. I guess it's a simple bug
* `Directory.items`. It works. But here you use expression `os.path.join(self.path, name)` four times. It is a bad practice for programmers. It is better to create variable with value of this expression and use this variable instead
* `Directory.files` and `Directory.subdirectories`. You have the same pieces of code in these methods and `Directory.items`. This problem can be solved in two ways:
    * Implement `items` using `files` and `subdirectories`:
        ```python
        def items(self):
            yield from self.files()
            yield from self.items()
        ````
    * Implement `files` and `subdirectories` using `items`:
        ```python
        def files(self):
            return filter(lambda x: x.isfile(), self.items())
        ````

**Comment by shpakb** [comment]
Fixed

**Comment by YakutovDmitriy** [comment]
Everything is ok
